export const ADD_RENDER_ITEM    = 'ADD_RENDER_ITEM'
export const EDIT_RENDER_ITEM    = 'EDIT_RENDER_ITEM'
export const ACTIVE_RENDER_ITEM = 'ACTIVE_RENDER_ITEM'
export const DROP_RENDER_ITEM = 'DROP_RENDER_ITEM'
